### ISSUE TITLE
Can't make this action work on a private repo

### ISSUE THREAD

**Issue by judahrand** [bufbuild/buf-breaking-action#65]
Just shows as failed with no useful output.

**Comment by doriable** [comment]
Hi, could you please provide more details with your issue?
Are you using this issue with a private Github repo or with a private BSR repository as the `--against` target? If you are using this with a private **BSR repository**, you must provide a `buf_token` as indicated in [the documentation](https://github.com/bufbuild/buf-breaking-action#configuration).

**Comment by judahrand** [comment]
Sorry, you're right this was unclear! I mean a private GitHub repo. I'm assuming that it fails to fetch the `--against` reference due to a lack of credentials.

**Comment by doriable** [comment]
Yes, so this has to do with the way your Github Actions job is configured.
If you are using `actions/checkout`, you should be able to access the same repository, for example:

```
on: pull_request # Apply to all pull requests
jobs:
  validate-protos:
    steps:
      # Run `git checkout`
      - uses: actions/checkout@v2
      # Install the `buf` CLI
      - uses: bufbuild/buf-setup-action@v1
      # Run breaking change detection against the `main` branch
      - uses: bufbuild/buf-breaking-action@v1
        with:
          against: 'https://github.com/acme/weather.git#branch=main'
```

This action is defined on `https://github.com/acme/weather.git`, and thus will be able to run `buf breaking` against the `main` branch.

This is outlined in the docs for the checkout action.
https://github.com/actions/checkout

> The auth token is persisted in the local git config. This enables your scripts to run authenticated git commands.

**Comment by judahrand** [comment]
That's exactly what I'm doing 🤔

**Comment by doriable** [comment]
This appears to have been resolved based on conversations in our public Slack channels. Please feel free to re-open and let me know if you need additional help on this :)

**Comment by judahrand** [comment]
@doriable Sort of 🤔  The docs still aren't very helpful for Private repos

**Comment by amit-ug** [comment]
@doriable this still does not work for me with a private repo:

Workflow:
```yaml
      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: "api"
          against: 
            "https://github.com/${{ github.repository }}.git#branch=main,ref=HEAD~1,subdir=api"
```

Output:
```
Run bufbuild/buf-breaking-action@v1
  with:
    input: api
    against: https://github.com/xxx/yyy.git#branch=main,ref=HEAD~1,subdir=api
    buf_input_https_username: zzz
    buf_input_https_password: ***
Failure: could not clone https://github.com/xxx/yyy.git: exit status 1
error: pathspec 'HEAD~1' did not match any file(s) known to git
Error: Failure: could not clone https://github.com/xxx/yyy.git: exit status 1
error: pathspec 'HEAD~1' did not match any file(s) known to git
```

**Comment by doriable** [comment]
@amit-ug So for `buf breaking`, if you are running it against a repository, the input needs to have the `#format=git`, which in your case would look like:

```
Run bufbuild/buf-breaking-action@v1
  with:
    input: api
    against: https://github.com/xxx/yyy.git#format=git,ref=main,ref=HEAD~1,subdir=api
    buf_input_https_username: zzz
    buf_input_https_password: ***
```

There are additional details in the documentation here: https://buf.build/docs/reference/inputs/source/#usage-3

Let me know if this helps!
